Repository microsoft/pxt, pull requests merged in 2018-05, with the labels that each got.

#4229 Port over accessibility menu from master
  docfiles/docs.html
  docfiles/style.css
  theme/accessibility.less
  theme/common.less
  webapp/src/app.tsx
Labels: v0

#4252 High contrast fixes
  package-lock.json
  theme/blockly-core.less
  theme/common.less
  theme/highcontrast.less
  theme/home.less
  webapp/src/app.tsx
  webapp/src/sui.tsx
  webapp/src/toolbox.tsx
Labels: accessibility

#4291 Thou shalt not load a script from an editor 1 major version above
  localtypings/pxtarget.d.ts
  webapp/src/app.tsx
Labels: Cherry pick to v0

#4316 Fix a number of accessibility issues
  theme/highcontrast.less
  theme/tutorial.less
  webapp/src/projects.tsx
  webapp/src/scriptsearch.tsx
Labels: v0

#4319 Fix issue with hidden image in the footer
  docfiles/footer.html
Labels: accessibility, v0
