Repository microsoft/pxt, pull requests merged in 2018-06, with the labels that each got.

#4427 Handle package load issues [v0]
  pxtlib/main.ts
  webapp/src/app.tsx
  webapp/src/package.ts
Labels: v0

#4432 Check shadow type on load
  pxtblocks/blocklyloader.ts
  pxtcompiler/emitter/decompiler.ts
Labels: Cherry pick to Master, v0

#4445 Match parsing of escapes in master
  pxtlib/service.ts
Labels: v0

#4468 Fix z index of grid picker tooltips on Edge
  theme/blockly-core.less
Labels: Cherry pick to Master

#4472 [cherry pick] Update documentation with scrolling / print fixes
  docfiles/docs.html
  docfiles/footer.html
  docfiles/header.html
  docfiles/style.css
  docfiles/toc.html
  docfiles/tocheader.html
  docfiles/vs.css
  pxtblocks/blocklyloader.ts
  theme/common.less
  theme/docs.less
  theme/pxt.less
  theme/themes/pxt/globals/site.variables
Labels: v0

#4470 Documentation page updates
  docfiles/docs.html
  docfiles/footer.html
  docfiles/header.html
  docfiles/style.css
  docfiles/toc.html
  docfiles/tocheader.html
  docfiles/vs.css
  pxtblocks/blocklyloader.ts
  pxtrunner/renderer.ts
  theme/common.less
  theme/docs.less
  theme/themes/pxt/globals/site.variables
  theme/tutorial.less
  webapp/public/run.html
Labels: Cherry pick to v0

#4473 Minor doc fix
  docfiles/style.css
Labels: Cherry pick to v0

#4487 BUiltin categories no longer in an export
  pxtlib/commonutil.ts
  pxtlib/service.ts
  webapp/src/blocks.tsx
  webapp/src/blocksSnippets.ts
  webapp/src/monaco.tsx
  webapp/src/monacoSnippets.ts
  webapp/src/toolbox.tsx
  webapp/src/toolboxeditor.tsx
Labels: :cop:DO NOT MERGE:cop:
