Repository microsoft/pxt, pull requests merged in 2018-04, with the labels that each got.

#4047 check if cookies are enabled when showing windows app banner
  pxtlib/analytics.ts
  webapp/src/notification.tsx
Labels: Cherry pick to v0

#4053 Cookies + Windows banner [v0]
  package-lock.json
  package.json
  pxtlib/analytics.ts
  webapp/src/blocks.tsx
  webapp/src/notificationbanner.tsx
Labels: v0

#4063 Don't use blockly ids when serializing xml.
  localtypings/blockly.d.ts
  pxtblocks/blocklyimporter.ts
  pxtblocks/blocklylayout.ts
Labels: Cherry pick to v0

#4064 [v0] Don't use blockly ids when serializing xml.
  localtypings/blockly.d.ts
  pxtblocks/blocklyimporter.ts
  pxtblocks/blocklylayout.ts
Labels: v0

#4103 don't show run button for ignored snippets
  docfiles/docs.js
  pxtrunner/renderer.ts
Labels: Cherry pick to v0

#4100 Move target logos into app cache
  cli/cli.ts
  pxtlib/browserutils.ts
  pxtlib/docsrender.ts
  webapp/public/release.manifest
  webapp/src/container.tsx
  webapp/src/projects.tsx
Labels: performance

#4125 Lazy blockly.css
  pxtlib/browserutils.ts
  webapp/public/index.html
Labels: performance

#4126 Bundle custom pxt icons
  cli/cli.ts
  webapp/public/docs.html
  webapp/public/index.html
  webapp/public/release.manifest
  webapp/public/siminstructions.html
Labels: performance

#4129 Bundle pxt*
  Jakefile.js
  webapp/public/index.html
  webapp/public/release.manifest
Labels: performance

#4132 Remove custom.css
  theme/blockly-core.less
  theme/common.less
  theme/debugger.less
  theme/monaco.less
  theme/pxt.less
  theme/themes/pxt/globals/site.variables
  theme/toolbox.less
  webapp/public/custom.css
  webapp/public/index.html
  webapp/public/release.manifest
  webapp/public/runnertest.html
  webapp/src/monaco.tsx
Labels: performance

#4138 allow loading scripts from other targets
  localtypings/pxtarget.d.ts
  pxtlib/cpp.ts
  webapp/src/app.tsx
Labels: Cherry pick to Master, v0

#4139 bundling worker scripts
  Jakefile.js
  docfiles/docs.js
  pxtlib/cpp.ts
  webapp/public/embed.js
  webapp/public/lzma/lzma_worker-min.js
  webapp/public/lzma/ossinfo.md
  webapp/public/release.manifest
  webapp/src/worker.ts
Labels: performance

#4145 don't change the title based on script
  webapp/src/app.tsx
  webapp/src/notification.tsx
Labels: Cherry pick to v0

#4153 Batch testing of approved packages [v0]
  cli/cli.ts
Labels: v0

#4146 Only load AI when cookie consent given
  docfiles/pxtweb/cookieCompliance.ts
Labels: Cherry pick to v0

#4147 [V0] Only load AI when cookie consent given
  docfiles/pxtweb/cookieCompliance.ts
Labels: v0

#4170 preload blockly on idle
  webapp/src/app.tsx
Labels: performance

#4101 No more Jquery and semantic.JS!
  Jakefile.js
  package-lock.json
  package.json
  pxtblocks/blocklyloader.ts
  pxteditor/editor.ts
  pxtlib/browserutils.ts
  pxtsim/accessibility.ts
  pxtsim/runtime.ts
  pxtsim/simdriver.ts
  theme/common.less
  theme/extension.less
  theme/home.less
  theme/themes/pxt/modules/modal.overrides
  webapp/public/index.html
  webapp/src/accessibility.tsx
  webapp/src/app.tsx
  webapp/src/blocks.tsx
  webapp/src/blockspreview.tsx
  webapp/src/carousel.tsx
  webapp/src/cmds.ts
  webapp/src/codecard.tsx
  webapp/src/container.tsx
  webapp/src/core.ts
  webapp/src/coretsx.tsx
  webapp/src/data.ts
  webapp/src/debugger.tsx
  webapp/src/dialogs.ts
  webapp/src/editortoolbar.tsx
  webapp/src/extensions.tsx
  webapp/src/filelist.tsx
  webapp/src/import.ts
  webapp/src/lang.tsx
  webapp/src/make.ts
  webapp/src/monaco.tsx
  webapp/src/notification.tsx
  webapp/src/projects.tsx
  webapp/src/pxtjson.tsx
  webapp/src/scriptsearch.tsx
  webapp/src/serial.tsx
  webapp/src/serialindicator.tsx
  webapp/src/share.tsx
  webapp/src/simtoolbar.tsx
  webapp/src/simulator.ts
  webapp/src/sui.tsx
  webapp/src/tutorial.tsx
Labels: performance

#4196 Use intersection observer on home screen
  webapp/src/codecard.tsx
Labels: performance
