Repository microsoft/pxt, pull requests merged in 2019-10, with the labels that each got.

#5991 Multiple tutorials per repo
  docs/writing-docs/user-tutorials.md
  pxtlib/github.ts
  webapp/src/app.tsx
Labels: cherry pick to microbit

#5996 align docs content left
  docfiles/style.css
  pxtlib/docsrender.ts
Labels: docs2.0

#6019 Refresh custom blocks
  webapp/src/blocks.tsx
  webapp/src/compiler.ts
Labels: cherry pick to microbit

#6035 Fix YouTube preview size
  docfiles/docs.js
Labels: docs2.0

#6013 doc TOC menu improvements
  docfiles/docs.js
  docfiles/macros.html
  docfiles/style.css
  docfiles/tocheader.html
  pxtlib/docsrender.ts
Labels: :cop:DO NOT MERGE:cop:

#6131 localizable user config
  cli/cli.ts
  webapp/src/pxtjson.tsx
Labels: cherry pick to microbit
